import { Inter } from "next/font/google"
import localFont from "next/font/local"
import styles from "./global.css"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})
const satoshi = localFont({
  src: "./Satoshi-Variable.ttf",
  display: "swap",
  variable: "--font-satoshi",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${satoshi.variable}`}>
      <body>{children}</body>
    </html>
  )
}
